#!/bin/bash

usage() { echo "Usage: $0 [-d <delete tag (string)>] [-c <create tag (string)>]" 1>&2; exit 1; }

replace_tag='false'
delete_tag=''
create_tag=''

while getopts ":d:c:" o; do
    case "${o}" in
        d)
            delete_tag=${OPTARG}
            ;;
        c)
            create_tag=${OPTARG}
            ;;
        *)
            echo ""
            usage
            ;;
    esac
done

shift $((OPTIND-1))

createTag() {
    IFS=','
    read -a tags <<< "$create_tag"

    for val in "${tags[@]}";
    do
        echo "tag to create ${val}"
        git tag ${val}
        git push origin ${val}
    done
    echo ""
}

deleteTag() {
    IFS=','
    read -a tags <<< "$delete_tag"

    for val in "${tags[@]}";
    do
        echo "tag to delete ${val}"
        git tag -d ${val}
        git push origin -d ${val}
    done
    echo ""
}


if [ "${delete_tag}" != "" ]; then
    deleteTag
fi

if [ "${create_tag}" != "" ]; then
    createTag
fi

if [ "${delete_tag}" == "" ] && [ "${create_tag}" == "" ]; then
    usage
fi

