#!/bin/bash

usage() { echo "Usage: $0 [-d <delete tag (string)>] [-c <create tag (string)>]" 1>&2; exit 1; }

replace_tag='false'
delete_tag=''
create_tag=''

while getopts ":d:c:" o; do
    case "${o}" in
        d)
            delete_tag=${OPTARG}
            ;;
        c)
            create_tag=${OPTARG}
            ;;
        *)
            echo ""
            usage
            ;;
    esac
done

shift $((OPTIND-1))

createTag() {
    echo "tag to create ${create_tag}"
    git tag ${create_tag}
    git push origin ${create_tag}
    echo ""

}

deleteTag() {
    echo "tag to delete: ${delete_tag}"
    git tag -d ${delete_tag}
    git push origin -d ${delete_tag}
    echo ""
}


if [ "${delete_tag}" != "" ]; then
    deleteTag
fi

if [ "${create_tag}" != "" ]; then
    createTag
fi

if [ "${delete_tag}" == "" ] && [ "${create_tag}" == "" ]; then
    usage
fi

